# Generated by Django 4.1.6 on 2023-02-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_prueba_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
