# Generated by Django 4.1.6 on 2023-02-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departamento', '0002_alter_departamento_shor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellido')),
                ('job', models.CharField(choices=[('1', 'ADMINISTRADOR'), ('3', 'ECONOMISTA'), ('4', 'OTRO'), ('0', 'CONTADOR')], max_length=1, verbose_name='Trabajo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamento.departamento')),
            ],
        ),
    ]
