# Generated by Django 4.1.6 on 2023-02-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('3', 'ECONOMISTA'), ('1', 'ADMINISTRADOR'), ('4', 'OTRO')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
