# Generated by Django 4.1.6 on 2023-02-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0003_habilidades_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='Persona.habilidades'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('3', 'ECONOMISTA'), ('1', 'ADMINISTRADOR'), ('0', 'CONTADOR'), ('4', 'OTRO')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
