# Generated by Django 4.1.6 on 2023-02-08 03:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0004_empleado_habilidades_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('3', 'ECONOMISTA'), ('1', 'ADMINISTRADOR'), ('4', 'OTRO'), ('0', 'CONTADOR')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
