# Generated by Django 4.1.6 on 2023-02-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0008_alter_empleado_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('4', 'OTRO'), ('3', 'ECONOMISTA')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
