# Generated by Django 4.1.6 on 2023-02-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0009_alter_habilidades_options_empleado_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('1', 'ADMINISTRADOR'), ('4', 'OTRO'), ('3', 'ECONOMISTA'), ('0', 'CONTADOR')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
