# Generated by Django 4.1.6 on 2023-02-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0015_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('4', 'OTRO'), ('3', 'ECONOMISTA'), ('1', 'ADMINISTRADOR'), ('0', 'CONTADOR')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
